-- Consulta SQL donde pueda obtener los productos vendidos digitando tipo de documento y número de documento.
SELECT  CLIENTES.TIPO_ID AS 'TIPO DE DOCUMENTO', CLIENTES.ID_CLIENTE AS 'DOCUMENTO', PRODUCTOS.DESCRIPCION AS 'PRODUCTO'
FROM PRODUCTOS
JOIN FACTURAS ON FACTURAS.ID_PRODUCTO = PRODUCTOS.ID_PRODUCTO
JOIN CLIENTES ON CLIENTES.ID_CLIENTE = FACTURAS.ID_CLIENTE 
WHERE TIPO_ID = 'TI'
AND CLIENTES.ID_CLIENTE = '1087031087';  
-- Consultar productos por medio del nombre, el cual debe mostrar quien o quienes han sido sus proveedores.
SELECT DESCRIPCION AS 'PRODUCTO', PROVEEDORES.NOMBRE AS 'PROVEEDOR' FROM PRODUCTOS
JOIN PROVEEDORES ON PRODUCTOS.ID_PROVEEDOR = PROVEEDORES.ID_PROVEEDOR
WHERE DESCRIPCION = 'Llave bristol T 7mm';